name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        uses: actions/setup-node@v4

